Improve commandline interface

diff --git a/ssjc b/ssjc
--- a/ssjc
+++ b/ssjc
@@ -6,18 +6,48 @@
 # - links: brew install links
 
 
-if [ $# -ne 1 ]; then
+where=hesla
+
+function usage {
 	s=`basename $0`
-	echo "usage: $s param"
-	exit 1
+	echo "Find definition of a Czech word in SSJČ (Slovník spisovného jazyka českého)"
+	echo "usage: $s [-v] word"
+	echo "	-v verbose (find all occurrences)"
+	exit $1
+}
+
+while getopts "hv" o; do
+case "$o" in
+    h)
+	usage
+	;;
+    v)
+	where=full_text
+	;;
+
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+esac
+done
+
+
+posargs=$(( $# - $OPTIND + 1 ))
+
+if [[ posargs -ne 1 ]]; then
+	usage 1
 fi
+
+w=${@:$OPTIND:1}
+
 
 #perl -pe 's/\*\*/\n\*/g' | \
 
 tmp=`mktemp`
 
 #perl -pe 's/[0-9]+\./\n/g' | \
-links -dump "http://ssjc.ujc.cas.cz/search.php?heslo=$1&where=full_text&hsubstr=no" | \
+links -dump "http://ssjc.ujc.cas.cz/search.php?heslo=$w&where=$where&hsubstr=no" | \
 	perl -pe 's/\*//g' | \
 	grep -v '\[ [A-Za-z]* *\] ' | \
 	perl -pe 's/†//g' | \
@@ -32,11 +62,11 @@ if [ $? -eq 0 ]; then
 	grep -v '^\s*statí.\s*$' | \
 	perl -pe 's/^   /\* /g' | \
 	perl -pe 's/^\*\s{4,50}/\t/g' | \
-	egrep --color=auto "$1|$"
+	egrep --color=auto "$w|$"
 else
 	cat $tmp | \
 	sed '1s/^\s*/\* /' | \
 	perl -pe 's/^\s+/\t/g' | \
-	egrep --color=auto "$1|$"
+	egrep --color=auto "$w|$"
 fi
 
